### ISSUE TITLE
Tips are not received for a newly created DOT account

### ISSUE THREAD

**Issue by maksimryndin** [paritytech/substrate-tip-bot#133]
Hi guys! Could you please help/clarify the following issue
Disclaimer: it's my first use of crypto :). 

**What has happened**

1. With the RP https://github.com/paritytech/polkadot-sdk/pull/2958 I was designated with a tip https://github.com/paritytech/polkadot-sdk/pull/2958#pullrequestreview-1827041871
2. So I've checked Polkadot site, chosen [Nova wallet](https://novawallet.io/) as a mobile app
3. created a wallet via a mnemonic with Nova app
4. copied the fresh DOT account address to the PR body.
5. After that the bot command was issued with a successful result https://github.com/paritytech/polkadot-sdk/pull/2958#issuecomment-1898451315
6. Tips are **not** received https://explorer.polkascan.io/polkadot/account/13zCyRG2a1W2ih5SioL8byqmQ6mc8vkgFwQgVzJSdRUUmp46

**Expected result**

Tips are received

**Comment by mordamax** [comment]
hello @maksimryndin!
The tips are submitted as referenda, which you can find in Small Tipper track in polkassembly for example
https://polkadot.polkassembly.io/referenda/429
https://polkadot.subscan.io/referenda_v2/429

in the Parameters you may find your address with proposed amount.
Once the proposal is approved and enacted, you will get your tip.

There's another problem though, which I noticed today #132, that might be annoying, but you can comment there with the explanation of this proposal and link to your PR as a workaround

**Comment by maksimryndin** [comment]
Hello @mordamax ! Thank you for a quick reply and supported issue! Will take some time to get to know more about Gov :)

**Comment by mordamax** [comment]
Sure, i'll close this issue for now, but if you have more questions, feel free to reopen or create a new one

**Comment by shawntabrizi** [comment]
maybe a small sentence that says "check the referenda for the progress of receiving your tip" or a direct link to the specific referenda could solve this confusion

**Comment by mordamax** [comment]
@shawntabrizi i think https://github.com/paritytech/substrate-tip-bot/issues/113 should give even better context

**Comment by maksimryndin** [comment]
> maybe a small sentence that says "check the referenda for the progress of receiving your tip" or a direct link to the specific referenda could solve this confusion

For complete newbies like me, perhaps the footnote in https://github.com/paritytech/polkadot-sdk/pull/2958#issuecomment-1898452221 that _funds are transfered within several days according to [some governance procedure](link to docs)_ would substantially clarify. As a natural expectation is that it is an ordinary transaction which should be fast.

**Comment by rzadp** [comment]
I proposed more precise wording: https://github.com/paritytech/substrate-tip-bot/pull/135
