### ISSUE TITLE
Review Dockerfile

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/substrate-tip-bot#16]
- [ ] Use `yarn --immutable` for installing dependencies (`--frozen-lockfile` is deprecated) https://github.com/paritytech/substrate-tip-bot/blob/5d55e2cd415ea2866e18e9a505cad0ca3100c2fe/Dockerfile#L13

**Comment by mordamax** [comment]
@joao-paulo-parity won't existing file work? 
https://github.com/paritytech/substrate-tip-bot/blob/master/Dockerfile

**Comment by joao-paulo-parity** [comment]
> @joao-paulo-parity won't existing file work? https://github.com/paritytech/substrate-tip-bot/blob/master/Dockerfile

Yes, although it needs to be reviewed so I'll repurpose this issue

**Comment by mordamax** [comment]
Done in #18
