### ISSUE TITLE
Make approvers team a link in messages, to ensure better UX

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-tip-bot#167]
There is no repo `paritytech/tip-bot-approvers`, so this warning / message is out of date and should be updated.

<img width="938" alt="image" src="https://github.com/user-attachments/assets/25c7bc2f-894a-47e0-821d-8cbcf3a106a9">

**Comment by mutantcornholio** [comment]
It's not a repo, it's a team: https://github.com/orgs/paritytech/teams/tip-bot-approvers. 
Any suggestions how to make it more obvious? We can use a link, for example

**Comment by shawntabrizi** [comment]
yeah turning the text into a clickable link would be good. perhaps also changing the link to match the format of the URL

**Comment by shawntabrizi** [comment]
I also made a request to join that team
