### ISSUE TITLE
BUG: Tip bot does not correctly use approvers list

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-tip-bot#169]
Karim is part of the approvers list.

<img width="1255" alt="image" src="https://github.com/user-attachments/assets/108cfac3-970f-4785-b15f-017431240669">

But the bot rejects his approval.

<img width="991" alt="image" src="https://github.com/user-attachments/assets/bd3692eb-1f0f-4745-b33c-350d16d89edc">

Is it potentially a problem with using the tip bot in a different org than paritytech?

**Comment by Bullrich** [comment]
First suggestion I would recommend is to remove him from the group and then add him again.

We faced a similar problem in the past where, for some unknown reason, a user appeared as a team member in the UI but not in the API.

**Comment by mordamax** [comment]
@KarimJedda please add a link
afair it was not a paritytech org, that could be a reason i guess

**Comment by mutantcornholio** [comment]
<img width="900" alt="Screen Shot 2024-09-03 at 10 53 36" src="https://github.com/user-attachments/assets/7eaef31c-63ed-4bfc-a107-ef7bb0389399">

According to GitHub at the time of the comment, @KarimJedda still wasn't a member of team

**Comment by shawntabrizi** [comment]
Yo @mutantcornholio, the issue persists, and its not cool to just close the issue without solving the problems being reported.

<img width="1396" alt="image" src="https://github.com/user-attachments/assets/a77e5a3e-c95c-458a-9c69-5a7ca77855e4">

**Comment by rzadp** [comment]
I believe that `404` is actually a `403` - no access to read that info from a different org.

We should either:

a) Create a separate `tip-bot-approvers` per each org.
b) Provide the bot deployment with some additional token with read access to `paritytech`'s org teams.

**Comment by mutantcornholio** [comment]
I think we're just using the wrong token here

We're [handling](https://github.com/paritytech/substrate-tip-bot/blob/64a795f29fee3d6e136c465abddca38e5e47f31d/src/bot-handle-comment.ts#L76) tip request with an installation octokitInstance that we use for replying in another org. 

[Here](https://github.com/paritytech/substrate-tip-bot/blob/64a795f29fee3d6e136c465abddca38e5e47f31d/src/bot-handle-comment.ts#L164-L167) we're using that token to query if tipRequester is a member of parity. 

Instead, we should either use [this one](https://github.com/paritytech/substrate-tip-bot/blob/64a795f29fee3d6e136c465abddca38e5e47f31d/src/bot-handle-comment.ts#L31-L36), or if it doesn't work then get a different installation token for our org, just how we did it for non-parity one.
