### ISSUE TITLE
Enforce linting rules on CI

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/substrate-tip-bot#17]
Either use a GitLab job for this (as demonstrated in https://github.com/paritytech/pr-custom-review/blob/4066ef64c8633fbc9a1b08a4d9442a784253f49a/.gitlab-ci.yml#L66 and https://github.com/paritytech/pr-custom-review/blob/4066ef64c8633fbc9a1b08a4d9442a784253f49a/.gitlab-ci.yml#L154) or a GitHub action (https://github.com/paritytech/opstooling-js-style/blob/a5b700ed4586dfead0ce3b5f7ff5d74f15b66cde/.github/workflows/pre-commit.yml#L49).

**Comment by rzadp** [comment]
Done.
