### ISSUE TITLE
[Feature] Also check for Polkadot Address in User Profile

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-tip-bot#182]
People in the Polkadot ecosystem constantly contributing might also have their address included in their profile.

For example like me:

<img width="339" alt="image" src="https://github.com/user-attachments/assets/b418f0cb-86b6-4731-aef2-732997853569">

This, for example, is the pattern needed for all Fellowship members to get their github verified.

It would be good that if we trigger a tip, that we can also check this user profile for the address, in case the user does not include it directly into their github pull request body.

This would be a fallback to the PR body check.

**Comment by mordamax** [comment]
@shawntabrizi we already have that, but parsing it a bit differently - similar to a PR body
https://github.com/paritytech/substrate-tip-bot/blob/master/src/util.ts#L65
`polkadot address: <ADDRESS>`

Do you suggest to use this address regardless of prefix or something else?

**Comment by shawntabrizi** [comment]
haha nice, sorry i didnt know.

thank you for thinking ahead for me :)
