### ISSUE TITLE
Suggestion - Display the link for an item in the tip proposal

### ISSUE THREAD

**Issue by paradox-tt** [paritytech/substrate-tip-bot#3]
Hi All,

![image](https://user-images.githubusercontent.com/79228812/134985943-eafb4c2a-d1ac-46e8-8d9e-e0020ab19eb7.png)

As shown in the above image, perhaps the full URL https://..../pull/9781 (https://github.com/paritytech/substrate/pull/9781) might be a better option?  It would certainly be easier for council members and on looking community members to access and view.

Regards,
Will | Paradox

**Comment by shawntabrizi** [comment]
@paradox-tt Yeah we just need to make sure the URL will fit into the text.

There should be a couple of logical branches:

* Figure out the maximum length allowed in a tip
* Try to construct a text with the full URL
* If it small enough, keep it
* If not, try generated a smaller text like the one currently used
*

**Comment by mordamax** [comment]
Will be done in scope of opengov polkassembly description https://github.com/paritytech/substrate-tip-bot/issues/62
