### ISSUE TITLE
Do not show error trace to the user

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate-tip-bot#32]
The bot currently is posting the full error context into a github comment. As an example see here: https://github.com/paritytech/substrate/pull/12723#issuecomment-1321700543

It should only post:
```
@bkchr ERROR: Error: Contributor did not properly post their account address.

Make sure the pull request description has: "{network} address: {address}".
```

**Comment by bkchr** [comment]
@parutger was the fix for this issue already deployed?

Because I just got it again: https://github.com/paritytech/substrate/pull/12833#issuecomment-1435262834

**Comment by parutger** [comment]
@bkchr Thanks for the feedback, It wasn't deployed to production yet.
