### ISSUE TITLE
fetch ALLOWED_USERS from github team

### ISSUE THREAD

**Issue by mordamax** [paritytech/substrate-tip-bot#33]
it doesn't make sense to store ALLOWED_USERS in vault because:
- we anyway output the list of users who should approve it
- we don't have visibility and open control for allowed users within org, if some user leaves company or becomes team lead

In order to simplify managing of allowed users - lets move it under the github team control
- create a team in GH (something like `tip bot approvers` or similar)
- add existing allowed users (as long as they are in ParityTech org) - shawntabrizi, gavofyork, rphmeier, athei, andresilva, arkpar, bkchr, eskimor, drahnr, dvdplm, robbepop, cmichi, tomaka, pepyakin, kianenigma, rossbulat
- implement dynamic check of allowed user using github api

**Comment by mutantcornholio** [comment]
The team: https://github.com/orgs/paritytech/teams/tip-bot-approvers/members

People, who aren't in @paritytech right now, so not in the list: drahnr, tomaka.

Now, to the question of who should maintain the team. Feels like we (meaning @paritytech/opstooling) shouldn't be **in** the team, so probably not us, right? 

cc/ @mordamax @lovelaced

**Comment by mutantcornholio** [comment]
done
