### ISSUE TITLE
openGov support

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate-tip-bot#39]
I've raised this in DM a few weeks ago as well, but I am worried that it will be forgotten until the day that we upgrade Polkadot to open gov as well and there'd be no way to tip anymore. 

To learn how to support this, all you have to do is follow more or less what I did here: 

https://kusama.polkassembly.io/referenda/69
1. open gov proposal with small spender 
2. submit preimage

---

@rzadp edits below

### Things left to figure out

- [x] Exact tip values corresponding to `small/medium/large` prompts
- [x] Chain-specific decimals, maximum tips per track, etc - Polkadot vs Kusama
- [x] Uploading tip (referendum) description
  - Either a polkassembly Description (off-chain),
  - Or a Remark (on-chain)
- [x] Automatically detect whether the chain supports gov1 or opengov. Send proper one with a single command.

**Comment by kianenigma** [comment]
ping on this ^^ Open gov is coming to Polkadot (PR already open) and is being removed from Kusama. This will stop working soon.

**Comment by kianenigma** [comment]
any updates on this?

**Comment by parutger** [comment]
I think I figured out how to implement this, but I'm having some trouble creating a local testing setup for this. Can you help me, or do you know who can?

**Comment by rzadp** [comment]
Hey @kianenigma, just letting know that I have picked up this issue.
I will be posting updates.

**Comment by rzadp** [comment]
Hey @kianenigma @bkchr, do you have any preference on how the new bot prompt for OpenGov should work when it comes to the exact tip values?

The difference is that in OpenGov we have to configure the tip value ahead of time, whereas in gov1 it was outside of the scope of the tip bot.

I have two proposals:

Prompt | Behavour
--- | ---
`/tip {small,medium,large}` or `/tip {small,big}`  | The bot looks up a corresponding constant value
`/tip <number>` | The bot proposes the tip with the given value, automatically picking the correct track (`Small Tipper / Big Tipper`)

**Comment by bkchr** [comment]
Maybe all? Fixed numbers for small, medium and large and then also tipping some custom number.

**Comment by mordamax** [comment]
@bkchr, with custom number it's clear, but with fixed - question: since the limits of small track are different per relay-chain, for small/medium/large what values would you suggest?

kusama small tipper: max 8.3 KSM - so 
- small: 2 KSM
- medium: 5KSM 
- large: 8KSM

polkadot small tipper: 250 DOT
- small: 20DOT
- medium: 80DOT
- large: 150DOT

or any other numbers?

**Comment by kianenigma** [comment]
Suggested numbers make sense as prelude defaults, and then as basti said I think it should be reasonable to allow `custom 42` to tip exactly this amount. I suppose you can still cap it to small tipper range.

**Comment by rzadp** [comment]
Hey @kianenigma @bkchr, just letting know that:

- The opengov changes have been implemented, so we'll be ready for the removal of treasury tips.
- We also implemented the custom numeric value for the tips.
- The changes are deployed to staging (not to production yet at the time of writing).

**Comment by bkchr** [comment]
Nice! Ty for the update!

**Comment by rzadp** [comment]
The changes are done and deployed to production.
