### ISSUE TITLE
Allow amount to be specified. 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate-tip-bot#41]
We can attract a whole lot more contributions if we can label a PR with `tip-medium`/`tip/large` so that contributors can know for which issues they can earn something. 

For example, now we finished the academy. How cool would it have been if we could attract them to make some contribution and earn tip? 

In the short term, we can just add a `tippable` label or something like that. 

cc @gpestana @the-right-joyce

**Comment by kianenigma** [comment]
Some of the points are duplicate of https://github.com/paritytech/substrate-tip-bot/issues/29

**Comment by abebeos** [comment]
@kianenigma , those labels would be nice, and in addition, the known `Help Wanted` should be used (thus the issues are mentioned within the repository overview)


* Potential contributor visits https://github.com/paritytech
* Finds a repository of interest, then selects e.g. the `n issues need help` link:
* (example, could be gone in future) https://github.com/paritytech/parity-bridges-common/issues?q=label%3A%22Help+Wanted%22+is%3Aissue+is%3Aopen
* If the labels you (and #29) mention are added (`tip-small/medium/large`) thus contributor can pick easily a task/tip size

**Comment by kianenigma** [comment]
Yes, let's close this.
