### ISSUE TITLE
Support Testnets

### ISSUE THREAD

**Issue by rzadp** [paritytech/substrate-tip-bot#46]
Currently, the tip bot supports `Polkadot`, `Kusama`, and a local development chain for development.

In order to play with a staging deployment of the bot, the only options are `Polkadot` and `Kusama`.
It's not a very useful staging environment if we can't play with it without using real money, so it would be useful to spend Testnet money instead.

**Comment by rzadp** [comment]
@paritytech/opstooling What do you think? Or am I missing something here?

**Comment by rzadp** [comment]
Community Testnets:

Testnet | Treasury | OpenGov
--- | --- | ---
[Westned](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.dotters.network%2Fwestend#/explorer) | no | no
[Rococo](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/treasury) | yes | yes

**Comment by mordamax** [comment]
prob just replace localtest* with localtest which will be rococo by default? 
just make it clear from settings and readme

**Comment by rzadp** [comment]
> prob just replace localtest* with localtest which will be rococo by default? just make it clear from settings and readme

I would like to keep `localtest*` pointing to `localhost:9944`, because that might be the only way for everyone to test the whole flow (including voting on the tip).

Also apart from adding the config, we need to have the bot account topped up on Rococo, and an alert added to (existing?) set of alerts.

**Comment by rzadp** [comment]
Small update: Rococo actually doesn't have the pallets I need. It has preimages and democracy, but the `Referenda` is missing.

<img width="221" alt="Screenshot 2023-04-24 at 11 24 00" src="https://user-images.githubusercontent.com/12039224/233955944-45dc828e-e597-43f1-9491-4e8daefd5c86.png">

So it looks like neither Westend nor Rococo can be used for this purpose.

**Comment by rzadp** [comment]
<img width="594" alt="Screenshot 2023-04-24 at 11 45 06" src="https://user-images.githubusercontent.com/12039224/233963849-bcdaf25f-4249-48f7-854a-551618f015d4.png">

Wococo is no good as well, there is neither Treasury nor OpenGov Referenda.

I couldn't find a websocket RPC of Versi anywhere.

**Comment by mordamax** [comment]
@lovelaced do you know how can we test opengov with testnet?

**Comment by rzadp** [comment]
PR to watch: https://github.com/paritytech/polkadot/pull/7272

**Comment by rzadp** [comment]
We now support Rococo and Westend:

- https://rococo.subsquare.io/referenda/38

Unfortunately Polkassembly integration could not be tested (Rococo and Westend Polkassembly sites are not working properly currently).
