### ISSUE TITLE
Make sure bot works properly when used simultaneously

### ISSUE THREAD

**Issue by rzadp** [paritytech/substrate-tip-bot#71]
We should test the bot when used simultaneously - make sure the nonces are not colliding, etc.
If needed, we should introduce locks around the blockchain transactions.

**Comment by mutantcornholio** [comment]
Just run all the tests in parallel :)

**Comment by rzadp** [comment]
The integration tests run in parallel by default, and we do have this important assertion to make sure we read back the proper referendum id:

https://github.com/paritytech/substrate-tip-bot/blob/52b9bba8b211d2de1b8d5afd7b6fa01e38c1b987/src/tip.integration.ts#L147-L150

So I think we're good on this front.
