### ISSUE TITLE
Queue Incomplete Tips and Try Again On Next Tip

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-tip-bot#8]
Sometimes not all the information is available for a tip when it is initially triggered, for example if a user does not initially post their Polkadot / Kusama address.

We should place the information about these PRs into a simple JSON DB, and then after the next time the tip bot is triggered, go through the JSON DB and try to complete the tip looking for the new information.

There should be a timeout after 7 days or something, and then we clean up the queued tip.

**Comment by mordamax** [comment]
Assuming that if someone have missed to "add all the information" -> "<chain> address" in time, until someone runs a `/tip <size>`, and bot saved it into a DB - how much time it would take until "after the next time the tip bot is triggered" and how likely the given PR will already have "all the information" in place? 

Bot currently notifies immediately if the info is missing and most likely contributor adds this sooner, and asks to re-trigger the tip. 
I hardly imagine if re-triggering would be delegated to some 3rd party events from other PRs or even from "on edit description" event, hoping that this would mean contributor just added an address. 
So i'd rather close this issue. May be i got it somehow wrong, so feel free to reopen

**Comment by shawntabrizi** [comment]
I think this idea can be replaced with the larger vision for the Async V2 Tip Bot here: https://github.com/paritytech/substrate-tip-bot/issues/29
